export default [
  {
    name: 'Спиннинг Medium 2.4м',
    slug: 'spinning-medium-24',
    categorySlug: 'spinning',
    brand: 'FishPro',
    price: 3500,
    oldPrice: 4200,
    images: ['/images/products/spinning.jpg'],
    specs: { length: '2.4м', test: '5-25г', material: 'карбон' },
    stock: 15,
    fishTags: ['щука', 'окунь', 'судак'],
    methodTags: ['спиннинг'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 90,
    description: 'Универсальный спиннинг для ловли хищника. Подходит для берега и лодки.',
  },
  {
    name: 'Воблер Minnow 90',
    slug: 'wobbler-minnow-90',
    categorySlug: 'wobbler',
    brand: 'AquaLure',
    price: 450,
    images: ['/images/products/wobbler.jpg'],
    specs: { length: '90мм', weight: '12г', type: 'minnow', depth: '0.5-1.5м' },
    stock: 50,
    fishTags: ['щука', 'окунь', 'жерех'],
    methodTags: ['спиннинг', 'твичинг'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 85,
    description: 'Классический минноу для твичинга. Стабильная игра на любой скорости.',
  },
  {
    name: 'Плетёный шнур 0.12мм 150м',
    slug: 'braid-012-150',
    categorySlug: 'braid',
    brand: 'LineMaster',
    price: 890,
    oldPrice: 1100,
    images: ['/images/products/braid.jpg'],
    specs: { diameter: '0.12мм', length: '150м', strands: 4, color: 'зелёный' },
    stock: 30,
    fishTags: ['щука', 'окунь', 'судак', 'карп'],
    methodTags: ['спиннинг', 'фидер'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 80,
    description: 'Прочный 4-жильный шнур для спиннинга и фидера.',
  },
  {
    name: 'Фидер Light 3.6м',
    slug: 'feeder-light-36',
    categorySlug: 'feeder',
    brand: 'FishPro',
    price: 4800,
    images: ['/images/products/feeder.jpg'],
    specs: { length: '3.6м', test: 'до 60г', sections: 3, material: 'карбон' },
    stock: 10,
    fishTags: ['карась', 'лещ', 'карп', 'плотва'],
    methodTags: ['фидер'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 75,
    description: 'Лёгкий фидер для ловли мирной рыбы на реках и озёрах.',
  },
  {
    name: 'Силиконовые виброхвосты 10шт',
    slug: 'soft-vibro-10',
    categorySlug: 'soft-bait',
    brand: 'AquaLure',
    price: 250,
    images: ['/images/products/soft-bait.jpg'],
    specs: { length: '75мм', count: 10, color: 'набор' },
    stock: 100,
    fishTags: ['окунь', 'щука', 'судак'],
    methodTags: ['спиннинг', 'джиг'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 70,
    description: 'Набор съедобного силикона для джига. Рабочие цвета.',
  },
  {
    name: 'Безынерционная катушка 3000',
    slug: 'spinning-reel-3000',
    categorySlug: 'spinning-reel',
    brand: 'ReelTech',
    price: 2800,
    oldPrice: 3200,
    images: ['/images/products/reel.jpg'],
    specs: { size: 3000, weight: '280г', gearRatio: '5.2:1', bearings: 5 },
    stock: 20,
    fishTags: ['щука', 'окунь', 'судак', 'карп'],
    methodTags: ['спиннинг', 'фидер'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 88,
    description: 'Надёжная катушка для спиннинга и фидера. Плавный ход.',
  },
  {
    name: 'Поплавочная удочка 5м',
    slug: 'float-rod-5',
    categorySlug: 'float-rod',
    brand: 'FishPro',
    price: 2200,
    images: ['/images/products/float-rod.jpg'],
    specs: { length: '5м', material: 'стекловолокно', sections: 5 },
    stock: 25,
    fishTags: ['карась', 'плотва', 'краснопёрка'],
    methodTags: ['поплавок'],
    seasonTags: ['весна', 'лето'],
    popularity: 60,
    description: 'Телескопическая поплавочная удочка для ловли мирной рыбы.',
  },
  {
    name: 'Прикормка универсальная 1кг',
    slug: 'groundbait-universal-1',
    categorySlug: 'groundbait',
    brand: 'BaitMix',
    price: 180,
    images: ['/images/products/groundbait.jpg'],
    specs: { weight: '1кг', type: 'универсальная' },
    stock: 200,
    fishTags: ['карась', 'лещ', 'карп', 'плотва'],
    methodTags: ['фидер', 'поплавок'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 65,
    description: 'Универсальная прикормка для мирной рыбы. Работает на любых водоёмах.',
  },
  {
    name: 'Спиннинг Light 2.1м',
    slug: 'spinning-light-21',
    categorySlug: 'spinning',
    brand: 'FishPro',
    price: 2900,
    images: ['/images/products/spinning-light.jpg'],
    specs: { length: '2.1м', test: '3-15г', material: 'карбон' },
    stock: 18,
    fishTags: ['окунь', 'щука', 'голавль'],
    methodTags: ['спиннинг', 'твичинг'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 82,
    description: 'Лёгкий спиннинг для ловли на малых реках. Тонкий кончик, дальний заброс.',
  },
  {
    name: 'Катушка безынерционная 4000',
    slug: 'spinning-reel-4000',
    categorySlug: 'spinning-reel',
    brand: 'ReelTech',
    price: 3400,
    oldPrice: 3900,
    images: ['/images/products/reel-4000.jpg'],
    specs: { size: 4000, weight: '310г', gearRatio: '5.1:1', bearings: 6 },
    stock: 14,
    fishTags: ['щука', 'судак', 'карп'],
    methodTags: ['спиннинг', 'фидер'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 78,
    description: 'Мощная катушка для тяжёлого спиннинга и фидера. 6 подшипников.',
  },
  {
    name: 'Блесна колеблющаяся 50мм',
    slug: 'spoon-50',
    categorySlug: 'spoon',
    brand: 'AquaLure',
    price: 380,
    images: ['/images/products/spoon.jpg'],
    specs: { length: '50мм', weight: '18г', type: 'колебалка', color: 'серебро' },
    stock: 60,
    fishTags: ['щука', 'судак', 'окунь'],
    methodTags: ['спиннинг'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 68,
    description: 'Классическая колеблющаяся блесна для ловли хищника.',
  },
  {
    name: 'Монофильная леска 0.20мм 100м',
    slug: 'mono-line-020-100',
    categorySlug: 'mono-line',
    brand: 'LineMaster',
    price: 320,
    images: ['/images/products/mono-line.jpg'],
    specs: { diameter: '0.20мм', length: '100м', color: 'прозрачный' },
    stock: 80,
    fishTags: ['карась', 'плотва', 'лещ', 'окунь'],
    methodTags: ['поплавок', 'фидер'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 55,
    description: 'Качественная монофильная леска для поплавочной и фидерной ловли.',
  },
  {
    name: 'Тройник №8 (10шт)',
    slug: 'treble-hook-8',
    categorySlug: 'treble-hook',
    brand: 'HookPro',
    price: 150,
    images: ['/images/products/hook.jpg'],
    specs: { size: '№8', count: 10, material: 'углеродистая сталь' },
    stock: 120,
    fishTags: ['щука', 'судак', 'окунь'],
    methodTags: ['спиннинг', 'твичинг'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 50,
    description: 'Острые тройники для воблеров и блёсен. Набор 10 штук.',
  },
  {
    name: 'Бойлы рыбные 8мм 500г',
    slug: 'boilies-fish-8',
    categorySlug: 'boilies',
    brand: 'BaitMix',
    price: 420,
    images: ['/images/products/boilies.jpg'],
    specs: { diameter: '8мм', weight: '500г', flavor: 'рыбный' },
    stock: 40,
    fishTags: ['карп', 'сазан', 'лещ'],
    methodTags: ['фидер', 'карпфишинг'],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 58,
    description: 'Рыбные бойлы для ловли карпа. Высокое содержание белка.',
  },
  {
    name: 'Ящик для рыбалки 2 слоя',
    slug: 'tackle-box-2',
    categorySlug: 'box',
    brand: 'BoxPro',
    price: 1900,
    oldPrice: 2300,
    images: ['/images/products/tackle-box.jpg'],
    specs: { layers: 2, material: 'пластик', compartments: 15 },
    stock: 22,
    fishTags: [],
    methodTags: [],
    seasonTags: ['весна', 'лето', 'осень'],
    popularity: 45,
    description: 'Вместительный ящик с двумя слоями и съёмными перегородками.',
  },
  {
    name: 'Сапоги болотные ЭВА',
    slug: 'boots-eva',
    categorySlug: 'boots',
    brand: 'FishWear',
    price: 2400,
    images: ['/images/products/boots.jpg'],
    specs: { material: 'ЭВА', size: '41-46', height: '40см' },
    stock: 30,
    fishTags: [],
    methodTags: [],
    seasonTags: ['весна', 'осень'],
    popularity: 40,
    description: 'Лёгкие тёплые сапоги для рыбалки. Непромокаемые.',
  },
];